# Generated by Django 2.2 on 2019-05-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_squashed_0002_auto_20190514_1255'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='unique_word_per_language'),
        ),
    ]
