# Generated by Django 2.2 on 2019-05-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20190520_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='words', related_query_name='word', to='words.Word'),
        ),
    ]
