# Generated by Django 2.2 on 2019-05-05 18:29

from django.db import migrations, models
import django.db.models.deletion
import words.models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_wordset'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='language',
            field=models.OneToOneField(default=words.models.default_language, on_delete=django.db.models.deletion.PROTECT, to='words.Language'),
        ),
    ]
