# Generated by Django 2.2 on 2019-05-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20190520_1738'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wordset',
            constraint=models.UniqueConstraint(fields=('name', 'creator'), name='unique_wordset_name_per_creator'),
        ),
    ]
