# Generated by Django 2.2 on 2019-05-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20190526_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordset',
            name='name',
            field=models.CharField(help_text='Enter a unique name for this set of words', max_length=100),
        ),
    ]
