# Generated by Django 2.2 on 2019-05-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_word_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordset',
            name='private',
        ),
    ]
