# Generated by Django 2.2 on 2019-05-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20190526_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='datamuse_success',
            field=models.BooleanField(default=False),
        ),
    ]
