# Generated by Django 2.2 on 2019-06-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_word_datamuse_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='ant',
            field=models.ManyToManyField(blank=True, related_name='antonyms', related_query_name='antonym', to='words.Word', verbose_name='antonyms'),
        ),
        migrations.AlterField(
            model_name='word',
            name='cns',
            field=models.ManyToManyField(blank=True, help_text='i.e. sample and simple', related_name='consonant_matches', related_query_name='consonant_match', to='words.Word', verbose_name='consonant matches'),
        ),
        migrations.AlterField(
            model_name='word',
            name='hom',
            field=models.ManyToManyField(blank=True, help_text='sound-alike words', related_name='homophones', related_query_name='homophone', to='words.Word', verbose_name='homophones'),
        ),
        migrations.AlterField(
            model_name='word',
            name='nry',
            field=models.ManyToManyField(blank=True, help_text='approximate rhymes', related_name='near_rhymes', related_query_name='near_rhyme', to='words.Word', verbose_name='near rhymes'),
        ),
        migrations.AlterField(
            model_name='word',
            name='rhy',
            field=models.ManyToManyField(blank=True, help_text='perfect rhymes', related_name='rhymes', related_query_name='rhyme', to='words.Word', verbose_name='rhymes'),
        ),
        migrations.AlterField(
            model_name='word',
            name='syn',
            field=models.ManyToManyField(blank=True, related_name='synonyms', related_query_name='synonym', to='words.Word', verbose_name='synonym'),
        ),
    ]
