# Generated by Django 2.2 on 2019-06-06 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_auto_20190605_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='ant',
        ),
        migrations.RemoveField(
            model_name='word',
            name='bga',
        ),
        migrations.RemoveField(
            model_name='word',
            name='bgb',
        ),
        migrations.RemoveField(
            model_name='word',
            name='cns',
        ),
        migrations.RemoveField(
            model_name='word',
            name='com',
        ),
        migrations.RemoveField(
            model_name='word',
            name='gen',
        ),
        migrations.RemoveField(
            model_name='word',
            name='hom',
        ),
        migrations.RemoveField(
            model_name='word',
            name='jja',
        ),
        migrations.RemoveField(
            model_name='word',
            name='jjb',
        ),
        migrations.RemoveField(
            model_name='word',
            name='nry',
        ),
        migrations.RemoveField(
            model_name='word',
            name='par',
        ),
        migrations.RemoveField(
            model_name='word',
            name='rhy',
        ),
        migrations.RemoveField(
            model_name='word',
            name='spc',
        ),
        migrations.RemoveField(
            model_name='word',
            name='syn',
        ),
        migrations.RemoveField(
            model_name='word',
            name='trg',
        ),
    ]
