# Generated by Django 2.2 on 2019-06-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_auto_20190607_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordset',
            name='words',
        ),
    ]
