# Generated by Django 2.2 on 2019-06-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_remove_wordset_words'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrences', models.IntegerField(default=1)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word')),
                ('wordset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.WordSet')),
            ],
        ),
        migrations.AddField(
            model_name='wordset',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='words', related_query_name='word', through='words.Membership', to='words.Word'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('word', 'wordset'), name='unique_word_per_wordset'),
        ),
    ]
