# Generated by Django 2.2.2 on 2019-07-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_auto_20190611_1135'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wordset',
            name='unique_wordset_name_per_creator',
        ),
        migrations.AlterField(
            model_name='wordset',
            name='name',
            field=models.CharField(help_text='Enter a unique name for this set of words', max_length=100, unique=True),
        ),
    ]
