# Generated by Django 2.2.4 on 2019-08-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_auto_20190701_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='unrecognized_words',
            field=models.TextField(blank=True),
        ),
    ]
